### ISSUE TITLE
在应用列表搜索时崩溃了，版本是最新代码编译的

### ISSUE THREAD

**Issue by Howard20181** [NekoInverter/EdXposedManagerR#12]
Build version: 4.5.7.7 
Build date: 1981-01-01 01:01:02 
Current date: 2020-11-21 22:36:32 
Device: Xiaomi MI 9 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 7(offset:7).state:66 androidx.recyclerview.widget.RecyclerView{4ea3814 VFED..... ......ID 0,0-1080,2111 #7f0a017b app:id/recyclerView}, adapter:d.a.a.a.j3.n@84828bd, layout:androidx.recyclerview.widget.LinearLayoutManager@2511eb2, context:org.meowcat.edxposed.manager.BlackListActivity@7168122
	at androidx.recyclerview.widget.RecyclerView$s.k(:66)
	at androidx.recyclerview.widget.RecyclerView$s.e(:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.z1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.k1(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.y0(:20)
	at androidx.recyclerview.widget.RecyclerView.t(Unknown Source:38)
	at androidx.recyclerview.widget.RecyclerView.r(:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(:2)
	at android.view.View.layout(View.java:22133)
	at android.view.ViewGroup.layout(ViewGroup.java:6330)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(Unknown Source:58)
	at android.view.View.layout(View.java:22133)
	at android.view.ViewGroup.layout(ViewGroup.java:6330)
	at b.c.a.c.d.g.C(:6)
	at b.c.a.c.d.h.k(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:4)
	at android.view.View.layout(View.java:22133)
	at android.view.ViewGroup.layout(ViewGroup.java:6330)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22133)
	at android.view.ViewGroup.layout(ViewGroup.java:6330)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22133)
	at android.view.ViewGroup.layout(ViewGroup.java:6330)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22133)
	at android.view.ViewGroup.layout(ViewGroup.java:6330)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22133)
	at android.view.ViewGroup.layout(ViewGroup.java:6330)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22133)
	at android.view.ViewGroup.layout(ViewGroup.java:6330)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:811)
	at android.view.View.layout(View.java:22133)
	at android.view.ViewGroup.layout(ViewGroup.java:6330)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3219)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2721)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1829)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7950)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1060)
	at android.view.Choreographer.doCallbacks(Choreographer.java:872)
	at android.view.Choreographer.doFrame(Choreographer.java:803)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1045)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7619)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Howard20181** [comment]
用的是这个版本
4849337ecdfa242232eddd115d3f7b827c94c409
